"""
Request/Response Schemas for Guard Microservice.
"""

from __future__ import annotations
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class EvaluationRequest(BaseModel):
    prompt: str = Field(..., description="Prompt text to evaluate")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Optional request metadata")


class EvaluationResponse(BaseModel):
    verdict_text: str = Field(..., description="Raw output generated by Guard model")
    confidence: float = Field(default=1.0, description="Confidence score")
    model_id: str = Field(..., description="Model identifier")
    model_revision: str = Field(default="v1", description="Model revision")
    latency_ms: float = Field(..., description="Inference latency in milliseconds")


class HealthResponse(BaseModel):
    status: str
    model_id: str
    device: str
