"""
Output Safety Engine — Post-Generation Security Filter.

Applies post-generation safety checks and redaction to all model outputs:
- Blocks responses with leaked cryptographic keys or AWS/API credentials (BLOCK)
- Blocks responses containing live exploit payloads or system prompt leaks (BLOCK)
- Redacts SSNs, Credit Cards, Emails, and Phone Numbers with standardized placeholders (REDACT)
- Passes clean responses without modification (ALLOW)
"""

from __future__ import annotations

import logging
from enum import Enum

from pydantic import BaseModel, Field

from output_safety.detectors.pii import OutputPIIDetector
from output_safety.detectors.policy import OutputPolicyDetector
from output_safety.detectors.secrets import SecretsDetector

logger = logging.getLogger(__name__)


class OutputVerdict(str, Enum):
    """Post-generation safety decision."""

    ALLOW = "ALLOW"
    REDACT = "REDACT"
    BLOCK = "BLOCK"


class OutputSafetyResult(BaseModel):
    """Result of post-generation safety filtering."""

    verdict: OutputVerdict = Field(..., description="ALLOW, REDACT, or BLOCK")
    sanitized_text: str = Field(..., description="Processed text safe for client return")
    reasons: list[str] = Field(default_factory=list, description="Detection reasons")
    detected_threats: dict[str, float] = Field(
        default_factory=dict, description="Category-to-score mappings"
    )
    is_modified: bool = Field(default=False, description="True if text was redacted or blocked")


class OutputSafetyEngine:
    """
    Central Output Safety Filter.
    Evaluates both Cloud (NORMAL) and Shield responses before returning to client.
    """

    def __init__(self) -> None:
        self.secrets_detector = SecretsDetector()
        self.pii_detector = OutputPIIDetector()
        self.policy_detector = OutputPolicyDetector()
        logger.info("OutputSafetyEngine initialized (Secrets, PII, and Policy detectors active)")

    def evaluate(self, response_text: str) -> OutputSafetyResult:
        """
        Evaluate and sanitize model response text.

        Args:
            response_text: The raw output text generated by the model.

        Returns:
            OutputSafetyResult with verdict, sanitized text, and telemetry.
        """
        if not response_text or not isinstance(response_text, str):
            return OutputSafetyResult(
                verdict=OutputVerdict.ALLOW,
                sanitized_text=response_text or "",
                reasons=[],
                detected_threats={},
                is_modified=False,
            )

        all_threats: dict[str, float] = {}
        reasons: list[str] = []

        # 1. Critical Secrets Check (BLOCK for scores >= 0.85)
        secret_scores = self.secrets_detector.evaluate(response_text)
        all_threats.update(secret_scores)
        if any(v >= 0.85 for v in secret_scores.values()):
            matched = [k for k, v in secret_scores.items() if v >= 0.85]
            reasons.extend([f"Critical secret detected: {m}" for m in matched])
            logger.warning("OutputSafety: BLOCK triggered by secret leak: %s", matched)
            return OutputSafetyResult(
                verdict=OutputVerdict.BLOCK,
                sanitized_text="[BLOCKED: Response contained sensitive security credentials or private keys]",
                reasons=reasons,
                detected_threats=all_threats,
                is_modified=True,
            )

        # 2. Exploits and Policy Violations Check (BLOCK for scores >= 0.85)
        policy_scores = self.policy_detector.evaluate(response_text)
        all_threats.update(policy_scores)
        if any(v >= 0.85 for v in policy_scores.values()):
            matched = [k for k, v in policy_scores.items() if v >= 0.85]
            reasons.extend([f"Policy violation: {m}" for m in matched])
            logger.warning("OutputSafety: BLOCK triggered by exploit payload or policy violation: %s", matched)
            return OutputSafetyResult(
                verdict=OutputVerdict.BLOCK,
                sanitized_text="[BLOCKED: Response contained restricted exploit payload or internal policy violation]",
                reasons=reasons,
                detected_threats=all_threats,
                is_modified=True,
            )

        # 3. PII Detection & Redaction (REDACT for scores > 0)
        pii_scores = self.pii_detector.evaluate(response_text)
        all_threats.update(pii_scores)
        if pii_scores:
            sanitized = self.pii_detector.redact(response_text)
            matched_pii = list(pii_scores.keys())
            reasons.extend([f"PII redacted: {m}" for m in matched_pii])
            logger.info("OutputSafety: REDACT triggered for PII: %s", matched_pii)
            return OutputSafetyResult(
                verdict=OutputVerdict.REDACT,
                sanitized_text=sanitized,
                reasons=reasons,
                detected_threats=all_threats,
                is_modified=sanitized != response_text,
            )

        # 4. Clean Output (ALLOW)
        return OutputSafetyResult(
            verdict=OutputVerdict.ALLOW,
            sanitized_text=response_text,
            reasons=[],
            detected_threats={},
            is_modified=False,
        )
